version: '3.11'

services:

  db_auth:
    container_name: postgresql_db
    image: postgres:14-alpine
    ports:
    - "5432:5432"
    expose:
    - 5432
    restart: always
    environment:
    - POSTGRES_PASSWORD=${POS_PASS}
    - POSTGRESS_USER=${POS_USER}
    - POSTGRES_DB=${DOK_DB}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - 5050:80
    depends_on:
      - db_auth

  fastapi:
    build: .
    container_name: money
    ports:
      - "8000:8000"
    depends_on:
      - db_auth
    restart: always
  


  
